### PR TITLE
Bug/nl fix movie page

### LINKED ISSUE #80: Movie-Page bug fix when no user logged in

### PR DESCRIPTION
**Pull request by NicoleLatifi**
### Type of change made:
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Styling- no new features

### Detailed Description / What does this PR do?

Added conditional statement so that the method that gets the user's rating only fires when a user is logged in.

### Files modified:

src/App/App.js
src/Movie-Page/Movie-Page.js

### Has This Been Tested?
- [ ] No
- [x] Yes

### Are there specific methods for testing?

Opened in browser and clicked on movie cards both logged out and logged in.

### What are the relevant tickets?

resolves #80 

### Message/Questions for reviewer:

It's fixed!

### Checklist:
- [x] My code has no unused/commented out code
- [x] My code has no console logs
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas

### CODE REVIEW

File: src/Movie-Page/Movie-Page.js [hunk 1]
```diff
@@ -25,7 +25,10 @@ class MoviePage extends Component {
 
   render() {
     const { movie, toggleMoviePage, currentUser } = this.props;
-    const currentUsersRating = this.getUserMovieRating();
+    let currentUsersRating;
+    if(currentUser) {
+      currentUsersRating = this.getUserMovieRating();
+    }
```
Comment (relyt4me) [inline src/Movie-Page/Movie-Page.js:31]: Glad we caught this in testing
